version: "3.9"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask_app:
    container_name: flask_app
    build: ./main
    ports:
      - "4010:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres_db:5432/postgres
    depends_on:
      - postgres_db

  flask_app2:
    container_name: flask_app2
    build: ./main
    ports:
      - "4011:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres_db:5432/postgres
    depends_on:
      - postgres_db
  
  flask_app3:
    container_name: flask_app3
    build: ./main
    ports:
      - "4012:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres_db:5432/postgres
    depends_on:
      - postgres_db
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "4000:80"
    depends_on:
      - flask_app
      - flask_app2
      - flask_app3
  
volumes:
  pgdata: