version: "3.9"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask_app:
    container_name: flask_app
    build: ./main
    ports:
      - "4010:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres_db:5432/postgres
      - PYSPARK_PYTHON=python3.10
      - PYSPARK_DRIVER_PYTHON=python3.10
    depends_on:
      - postgres_db
      - spark
      - kafka
      - zookeeper

  flask_app2:
    container_name: flask_app2
    build: ./main
    ports:
      - "4011:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres_db:5432/postgres
      - PYSPARK_PYTHON=python3.10
      - PYSPARK_DRIVER_PYTHON=python3.10
    depends_on:
      - postgres_db
      - spark
      - kafka
      - zookeeper
  
  flask_app3:
    container_name: flask_app3
    build: ./main
    ports:
      - "4012:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres_db:5432/postgres
      - PYSPARK_PYTHON=python3.10
      - PYSPARK_DRIVER_PYTHON=python3.10
    depends_on:
      - postgres_db
      - spark
      - kafka
      - zookeeper
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "4000:80"
    depends_on:
      - flask_app
      - flask_app2
      - flask_app3
      - postgres_db
      - spark
      - kafka
      - zookeeper

  spark:
    container_name: spark
    build: ./spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    volumes:
      - ./spark/postgresql-42.7.1.jar:/spark/postgresql-42.7.1.jar

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      #- KAFKA_CREATE_TOPICS: "trigger:1:1"
    depends_on:
      - zookeeper

  kafka-setup:
    image: bitnami/kafka:latest
    depends_on:
      - kafka
    command:
      - /bin/bash
      - -c
      - |
        apt-get update && apt-get install -y netcat &&
        ./wait-for-it.sh kafka:9092 --strict --timeout=300 -- 
        /opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic spark_trigger

  zookeeper:
    container_name: zookeeper
    restart: always
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
volumes:
  pgdata: