version: "3.9"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask_app:
    container_name: flask_app
    build: ./main_flask_app
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres_db:5432/postgres
    depends_on:
      - postgres_db
    
volumes:
  pgdata: